export const LoginTypes = {
    SIGN_IN_REQUEST: 'login/SIGN_IN_REQUEST',
    SIGN_IN_SUCCESS: 'login/SIGN_IN_SUCCESS',
    SIGN_IN_FAILURE: 'login/SIGN_IN_FAILURE',

    //SIGN_OUT_REQUEST: 'login/SIGN_OUT_REQUEST',
    //SIGN_OUT_SUCCESS: 'login/SIGN_OUT_SUCCESS',
    //SIGN_OUT_FAILURE: 'login/SIGN_OUT_FAILURE',
}